branches:
  except:
  - travis

environment:
  matrix:
  - PYTHON: Python26
  - PYTHON: Python27
  - PYTHON: Python33
  - PYTHON: Python34
  - PYTHON: Python35
  - PYTHON: Python36
  - PYTHON: Python37

install:
- set PATH=C:\\%PYTHON%;%PATH%
- python --version

build: off

test_script:
- set PYTHONPATH=%APPVEYOR_BUILD_FOLDER%
- python test/test.py --verbose

# vim:ts=2 sts=2 sw=2 et
