language: python
python:
- "2.6"
- "2.7"
- "pypy"
- "3.2"
- "3.3"
- "3.4"
- "nightly"
- "pypy3"
script:
- python setup.py build
- cp -r build/lib*/slownie.py test/
- python test/test.py --verbose

# vim:ts=2 sts=2 sw=2 et
