dist: trusty
language: python
jobs:
  include:
  - python: "2.6"
  - python: "2.7"
  - python: pypy
  - python: "3.2"
  - python: "3.3"
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
    dist: xenial
  - python: pypy3
branches:
  except:
  - appveyor
before_install:
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then pyflakes='pyflakes<2'; fi
- if [[ $TRAVIS_PYTHON_VERSION = 3.[23] ]]; then pyflakes='pyflakes<2'; fi
install:
- pip install pydiatra $pyflakes
script:
- dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
- python -m pydiatra .
- pyflakes .
- PYTHONPATH=$PWD python test/test.py --verbose
- LC_ALL=C python setup.py --version
- python setup.py install
- cd /
- python -c 'import slownie'

# vim:ts=2 sts=2 sw=2 et
